name: directus
description: The unofficial SDK for Directus, with REST API and auth. Compatible with Flutter.
version: 0.0.2
homepage: https://www.directus.io

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dependencies:
  dio: ^3.0.0
  hive: ^1.4.4+1

#  path: ^1.7.0

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
