name: directus
description: The unofficial SDK for Directus, with REST API and auth. Compatible with Flutter.
version: 0.6.0
homepage: https://www.directus.io
repository: https://github.com/apstanisic/directus-dart
issue_tracker: https://github.com/apstanisic/directus-dart/issues

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dependencies:
  # Http client
  dio: ^4.0.0
  # Storage
  shared_preferences: ^2.0.5
  # Annotations
  meta: ^1.3.0
  # Used for decorators for JSON serialization
  json_annotation: ^4.0.1
  # We need Flutter because `shared_preferences` does not work without it
  flutter:
    sdk: flutter

dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.17.3
  mockito: ^5.0.7
  json_serializable: ^4.1.1
  build_runner: ^2.0.2
